# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fangan.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import pandas as pd

class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super(QtWidgets.QMainWindow,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1596, 885)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.setWindowIcon(QIcon('ABC.ico'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ReadExcelButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReadExcelButton.setMaximumSize(QtCore.QSize(128, 28))
        self.ReadExcelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ReadExcelButton.setObjectName("ReadExcelButton")
        self.gridLayout.addWidget(self.ReadExcelButton, 0, 3, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMaximumSize(QtCore.QSize(380, 61))
        self.graphicsView.setObjectName("ABCImg")

        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.W_Button = QtWidgets.QPushButton(self.centralwidget)
        self.W_Button.setMaximumSize(QtCore.QSize(126, 28))
        self.W_Button.setObjectName("W_Button")
        self.horizontalLayout_4.addWidget(self.W_Button)
        self.A_Button = QtWidgets.QPushButton(self.centralwidget)
        self.A_Button.setMaximumSize(QtCore.QSize(126, 28))
        self.A_Button.setObjectName("A_Button")
        self.horizontalLayout_4.addWidget(self.A_Button)
        self.B_Button = QtWidgets.QPushButton(self.centralwidget)
        self.B_Button.setMaximumSize(QtCore.QSize(126, 28))
        self.B_Button.setObjectName("B_Button")
        self.horizontalLayout_4.addWidget(self.B_Button)
        self.C_Button = QtWidgets.QPushButton(self.centralwidget)
        self.C_Button.setObjectName("C_Button")
        self.horizontalLayout_4.addWidget(self.C_Button)
        self.D_Button = QtWidgets.QPushButton(self.centralwidget)
        self.D_Button.setObjectName("D_Button")
        self.horizontalLayout_4.addWidget(self.D_Button)
        self.E_Button = QtWidgets.QPushButton(self.centralwidget)
        self.E_Button.setObjectName("E_Button")
        self.horizontalLayout_4.addWidget(self.E_Button)
        self.G_Button = QtWidgets.QPushButton(self.centralwidget)
        self.G_Button.setObjectName("G_Button")
        self.horizontalLayout_4.addWidget(self.G_Button)
        self.H_Button = QtWidgets.QPushButton(self.centralwidget)
        self.H_Button.setObjectName("H_Button")
        self.horizontalLayout_4.addWidget(self.H_Button)
        self.K_Button = QtWidgets.QPushButton(self.centralwidget)
        self.K_Button.setObjectName("K_Button")
        self.horizontalLayout_4.addWidget(self.K_Button)
        self.I_Button = QtWidgets.QPushButton(self.centralwidget)
        self.I_Button.setObjectName("I_Button")
        self.horizontalLayout_4.addWidget(self.I_Button)
        self.J_Button = QtWidgets.QPushButton(self.centralwidget)
        self.J_Button.setObjectName("J_Button")
        self.horizontalLayout_4.addWidget(self.J_Button)
        self.L_Button = QtWidgets.QPushButton(self.centralwidget)
        self.L_Button.setObjectName("L_Button")
        self.horizontalLayout_4.addWidget(self.L_Button)
        self.M_Button = QtWidgets.QPushButton(self.centralwidget)
        self.M_Button.setObjectName("M_Button")
        self.horizontalLayout_4.addWidget(self.M_Button)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 5)

        self.BeginButton = QtWidgets.QPushButton(self.centralwidget)
        self.BeginButton.setMaximumSize(QtCore.QSize(128, 28))
        self.BeginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BeginButton.setObjectName("BeginButton")

        self.gridLayout.addWidget(self.BeginButton, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        #设置列宽和行高

        self.tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Interactive)
        self.tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # self.tableWidget.setRowHeight(0, 400)
        # self.tableWidget.setRowHeight(1, 400)
        # self.tableWidget.setRowHeight(2, 400)

        #设置列宽和行高
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 5)
        self.ABCDC_label = QtWidgets.QLabel(self.centralwidget)
        self.ABCDC_label.setMaximumSize(QtCore.QSize(551, 41))
        font = QtGui.QFont()
        font.setFamily("Yuanti SC")
        font.setPointSize(18)
        self.ABCDC_label.setFont(font)
        self.ABCDC_label.setTextFormat(QtCore.Qt.AutoText)
        self.ABCDC_label.setObjectName("ABCDC_label")
        self.gridLayout.addWidget(self.ABCDC_label, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.ReadExcelButton.clicked.connect(self.openfile)
        self.ReadExcelButton.clicked.connect(self.creat_table_show)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "应急演练计时"))
        self.ReadExcelButton.setText(_translate("MainWindow", "导入模板"))
        self.W_Button.setText(_translate("MainWindow", "电气领班W"))
        self.A_Button.setText(_translate("MainWindow", "高配A"))
        self.B_Button.setText(_translate("MainWindow", "高配B"))
        self.C_Button.setText(_translate("MainWindow", "变电站C"))
        self.D_Button.setText(_translate("MainWindow", "变电站D"))
        self.E_Button.setText(_translate("MainWindow", "变电站E"))
        self.G_Button.setText(_translate("MainWindow", "柴发G"))
        self.H_Button.setText(_translate("MainWindow", "柴发H"))
        self.K_Button.setText(_translate("MainWindow", "暖通领班K"))
        self.I_Button.setText(_translate("MainWindow", "冷站I"))
        self.J_Button.setText(_translate("MainWindow", "冷站J"))
        self.L_Button.setText(_translate("MainWindow", "精密空调L"))
        self.M_Button.setText(_translate("MainWindow", "环境处M"))
        self.BeginButton.setText(_translate("MainWindow", "开始演练"))
        self.ABCDC_label.setText(_translate("MainWindow", "中国农业银行北方数据中心应急演练方案"))

    def openfile(self):
        ###获取路径===================================================================
        openfile_name = QFileDialog.getOpenFileName(self, '选择文件', '', 'Excel files(*.xlsx , *.xls, *.wps, *.et, *.ett)')
        # print(openfile_name)
        global path_openfile_name
        ###获取路径====================================================================
        path_openfile_name = openfile_name[0]
        # print(path_openfile)

    def creat_table_show(self):
        ###===========读取表格，转换表格，===========================================
        if len(path_openfile_name) > 0:
            frame_all = pd.read_excel(path_openfile_name,index_col=0)
            # print(frame_all)
            frame_rows = frame_all.shape[0]
            frame_cols = frame_all.shape[1]
            # print(frame_rows)
            # print(frame_cols)
            #读取表格行/列表头
            frame_h_header = frame_all.columns.values.tolist()
            frame_v_header = frame_all.index.values.tolist()
            ###======================给tablewidget设置行列表头============================
            self.tableWidget.setColumnCount(frame_cols)
            self.tableWidget.setRowCount(frame_rows)
            self.tableWidget.setHorizontalHeaderLabels(frame_h_header)
            self.tableWidget.setVerticalHeaderLabels(frame_v_header)

            ###================遍历表格每个元素，同时添加到tablewidget中========================
            for j in range(frame_cols):
                input_table_cols_list = frame_all[frame_all.columns[j]].values.tolist()
                # button_start = QPushButton(str(input_table_cols_list[0]))
                # button_start.setStyleSheet('''text-align:center;background-color:DarkSeaGreen;height:30px;border-style:outset;font:14px''')
                # btnItem = QTableWidgetItem(str(input_table_cols_list[0]))
                # self.tableWidget.setStyleSheet(button_start,btnItem)
                for i in range(0,frame_rows):
                    input_table_item = input_table_cols_list[i]
                    ###==============将遍历的元素添加到tablewidget中并显示=======================
                    input_table_item = str(input_table_item)
                    # print(input_table_item)
                    newItem = QTableWidgetItem(input_table_item)
                    newItem.setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
                    self.tableWidget.setItem(i, j, newItem)
        else:
            self.centralWidget.show()